routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
|
 */

// Route::prefix('home')->group(function(){
//     Route::get('/','LandrickController@index')->name('landrick.index');
//     Route::get('/about', 'LandrickController@aboutPage')->name('landrick.about');
//     Route::get('/cloud-minning', 'LandrickController@cloudMinningPage')->name('landrick.cloud-mining');
//     Route::get('/faq','LandrickController@faqPage')->name('landrick.faq');
//     Route::get('/contact', 'LandrickController@contact')->name('landrick.contact');
//     Route::get('/buy-bitcoin', 'LandrickController@buyBitcoinPage')->name('landrick.buy-bitcoin');
//     Route::get('/how-it-works', 'LandrickController@howItWorks')->name('landrick.how-it-works');
//     Route::get('/privacy-policy', 'LandrickController@privacyPolicy')->name('landrick.privacy-policy');
//     Route::get('/terms-condition', 'LandrickController@termsCondition')->name('landrick.terms.condition');
//     Route::get('/private-equity', 'LandrickController@privateEquity')->name('landrick.private.equity');
//     Route::get('/investment-plans', 'LandrickController@InvestmentPlans')->name('landrick.investment');
//     Route::get('/dictionary', 'LandrickController@dictionary')->name('landrick.dictionary');
//     Route::get('/security', 'LandrickController@security')->name('landrick.security');
//     Route::get('/business', 'LandrickController@business')->name('landrick.business');
//     Route::get('/affiliates', 'LandrickController@affiliates')->name('landrick.affiliates');

//     Route::get('/plans/oil-gas', 'LandrickController@oilgasPage')->name('landrick.oil.gas');
//     Route::get('/plans/gold-investments', 'LandrickController@goldInv')->name('landrick.gold.inv');
//     Route::get('/plans/real-estate-investments', 'LandrickController@realEstate')->name('landrick.real.estate');
//     Route::get('/plans/agricultural-infrastructure-investments', 'LandrickController@agriInfra')->name('landrick.agri.infra');
//     Route::get('/plans/forex-investments', 'LandrickController@forex')->name('landrick.forex');
//     Route::get('/plans/crypto-investments', 'LandrickController@crypto')->name('landrick.crypto');

//     //Newsletter
//     Route::post('/newsletter-subscribe', 'NewsletterController@store')->name('newsletter.store');
//     Route::post('/contact-alert', 'NewsletterController@contactEmailAlert')->name('contact.alert');
// });

Route::middleware(['web'])->group(function () {
    Route::get('/session/set', function (Request $request) {
        Session::put('duru', 'This is a test session value.');
        return 'Session value has been set.';
    });

    Route::get('/session/get', function (Request $request) {
        $value = Session::get('duru', 'Default value if not set');
        return 'Session value: ' . $value;
    });

    Route::get('/session/clear', function (Request $request) {
        session()->forget('key');
        return 'Session value has been cleared.';
    });
});
// ///////////////////   User Routes  ///////////////////////
Auth::routes(['except' => ['verification.verify', 'verification.resend', 'logout']]);
Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify')->middleware('signed');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');

// Define a new login route
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');

Route::get('login/{provider}', 'Auth\LoginController@redirectToSocial')->name('social.login');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleSocialCallback')->name('social.login.callback');
Route::post('logout/', 'Auth\LoginController@logout')->name('auth.logout');

//2FA
Route::get('verify-otp', 'Auth\TwoFAController@show2faPage')->middleware(['auth', 'verified'])->name('otp.index');
Route::post('verify-otp', 'Auth\TwoFAController@store')->name('otp.store');
Route::post('verify-otp/resend', 'Auth\TwoFAController@resend')->name('otp.resend');

Route::get('preview-notification', function () {
    $markdown = new \Illuminate\Mail\Markdown(view(), config('mail.markdown'));
    $data = "Your data to be use in blade file";
    return $markdown->render("mail.regconfirm", [$data]);
});

Route::get('/user/verify/btc/payment', 'userController@btc_payment_suc');
Route::get('/reset/password/{username}/{token}', 'userController@pwd_req_verify');
Route::get('/registration/confirm/{usr}/{code}', 'Auth@verify_reg')->name('registration.confirm.link');
Route::get('/user/payment/{payAmt}/successful', 'userController@payment_suc')->middleware('auth', );
Route::get('/user/update/readmsg/{id}', 'userController@readmsg_up')->middleware('auth', );
Route::get('/user/get/states/{id}', 'userController@states');
Route::get('/user/get/countryCode/{id}', 'userController@countryCode');
Route::get('/user/remove/bankaccount/{id}', 'userController@deleteBankAccount')->middleware('auth', );
Route::post('/user/wallet/bank_deposit', 'userController@bank_deposit');

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////  admin /////////////////////////////////////////////////////////////////////

Route::prefix('back-end')->group(function () {
    Route::get('/', 'Auth\Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('/', 'Auth\Admin\LoginController@login')->name('admin.login.submit');
    Route::post('/back-end/logout', 'Auth\Admin\LoginController@logout')->name('admin.logout');

});
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\DashboardController@index')
        ->name('dashboard');
    Route::get('/manage/users', 'Admin\DashboardController@manageUsers')
        ->name('users');
    Route::get('/view/settings', 'Admin\DashboardController@settingsPage')->name('settings');
    Route::post('/update/site/settings', 'Admin\DashboardController@adminUpdatSettings')->name('update.settings');
    Route::get('/view/userdetails/{id}', 'Admin\DashboardController@viewUser')->name('view.user');
    Route::get('/activate/kyc/{id}', 'Admin\DashboardController@activateKyc');
    Route::get('/deactivate/kyc/{id}', 'Admin\DashboardController@deactivateKyc');
    Route::post('/update/user/profile', 'Admin\DashboardController@updateUserProfile');
    Route::post('/change/user/pwd', 'Admin\DashboardController@changeUserPwd');
    Route::get('/block/user/{id}', 'Admin\DashboardController@blockUser');
    Route::get('/activate/user/{id}', 'Admin\DashboardController@activateUser');
    Route::get('/delete/user/{id}', 'Admin\DashboardController@deleteUser');

    Route::get('/manage/investments', 'Admin\DashboardController@manageInvestmentsPage')->name('investments');
    Route::get('/pause/user_inv/{id}', 'Admin\DashboardController@pauseInv');
    Route::get('/activate/user_inv/{id}', 'Admin\DashboardController@activateInv');
    Route::get('/delete/user_inv/{id}', 'Admin\DashboardController@deleteInv');
    Route::get('/edit/user_inv/{id}', 'Admin\DashboardController@editInv');
    Route::post('/update/user_inv/{id}', 'Admin\DashboardController@updateInv')->name('update.investment');
    Route::post('/search/investment', 'Admin\DashboardController@searchInv');
    Route::get('/manage/adminUsers', 'Admin\DashboardController@manageAdminUsers')->name('manageAdmin.users');
    Route::post('/addNew/admin', 'Admin\DashboardController@admAddnew');

    Route::get('/manage/deposits', 'Admin\DashboardController@manageDepositsPage')->name('manageDeposits');
    Route::get('/reject/user/payment/{id}', 'Admin\DashboardController@rejectDep')->name('deposit.decline');
    Route::get('/approve/user/payment/{id}', 'Admin\DashboardController@approveDep')->name('deposit.approve');
    Route::get('/delete/user/payment/{id}', 'Admin\DashboardController@deleteDep')->name('deposit.delete');
    Route::post('/search/xinvestment', 'Admin\DashboardController@searchXInv');
    Route::post('/search/deposit', 'Admin\DashboardController@searchDep');
    Route::get('/add/deposits', 'Admin\DashboardController@addDeposit')->name('add.deposit');
    Route::post('/save/deposit', 'Admin\DashboardController@storeDeposit')->name('save.deposit');

    Route::get('/manage/withdrawals', "Admin\DashboardController@manageWithdrawalsPage")->name('manage.withdrawals');
    Route::get('/reject/user/wd/{id}', 'Admin\DashboardController@rejectWD');
    Route::get('/approve/user/wd/{id}', 'Admin\DashboardController@approveWD');
    Route::get('/delete/user/wd/{id}', 'Admin\DashboardController@deleteWD');
    Route::post('/search/Withdrawal', 'Admin\DashboardController@searchWD');

    Route::get('/manage/packages', 'Admin\DashboardController@managePackages')->name('manage.packages');
    Route::get('/delete/pack/{id}', 'Admin\DashboardController@adminDeletePack');
    Route::get('/create/package', 'Admin\DashboardController@create_package');
    Route::post('/create/package', 'Admin\DashboardController@create_package_post');
    Route::post('/edit/packages', 'Admin\DashboardController@editPack');

    Route::get('/act_deact/pack/{id}', 'Admin\DashboardController@switch_pack');
    Route::get('/send/msg', 'Admin\DashboardController@sendMsg')->name('send.msg');
    Route::post('/send/notification', 'Admin\DashboardController@admSendMsg');

resources/views/admin/add_deposit.blade.php
<?php    
    if(Session::has('val'))
    {
        $v = Session::get('val');
        $deps = App\deposits::where('user_id', 'like', '%'.$v.'%')->orwhere('usn', 'like', '%'.$v.'%')->orwhere('amount', 'like', '%'.$v.'%')->orwhere('bank', 'like', '%'.$v.'%')->orwhere('account_no', 'like', '%'.$v.'%')->orwhere('account_name', 'like', '%'.$v.'%')->orwhere('status', 'like', '%'.$v.'%')->orwhere('created_at', 'like', '%'.$v.'%')->orderby('id', 'desc')->paginate(100);
        Session::forget('val');
    }
    else
    {
        $deps = App\deposits::orderby('id', 'desc')->paginate(50);
    }
    
?>

@extends('admin.atlantis.layout')
@Section('content')
        <div class="main-panel">
            <div class="content">
                @include('admin.atlantis.main_bar')
                <div class="page-inner mt--5">
                    @include('admin.atlantis.overview')
                    <div id="prnt"></div>  
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <div class="card">
                                <div class="card-header card_header_bg_blue" >
                                    <div class="card-head-row card-tools-still-right">
                                        <h4 class="card-title text-white" > <i class="fas fa-donate"></i> {{ __('Add Deposit') }} </h4>
                                        
                                                                                                               
                                    </div>
                                </div>
                                <div class="card-body pb-0 table-responsive">
                                    @include('admin.temp.add_deposits')
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

resources/views/admin/add_package.blade.php
@extends('admin.atlantis.layout')
@Section('content')
    <div class="main-panel">
        <div class="content">
            @include('admin.atlantis.main_bar')
            <div class="page-inner mt--5">
                @include('admin.atlantis.overview')
                <div id="prnt"></div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card_header_bg_blue">
                                <div class="card-head-row card-tools-still-right">
                                    <h4 class="card-title text-white">
                                        <i class="fas fa-plus"></i>{{ __('Add Investment Packages') }}
                                    </h4>
                                </div>
                            </div>
                            <div class="card-body pb-0 table-responsive">
                                <form id="add_new_pack" action="/admin/create/package" method="post">
                                    @csrf()
                                    <div class="form-group row">
                                        <div class="col-sm-12">
                                            <label for="package_name">{{ __('Package Name') }}</label>
                                            <input id="package_name" type="text" class="regTxtBox" name="package_name"
                                                value="" required autocomplete="package_name" autofocus
                                                placeholder="Package Name">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="min">{{ __('Min Investment Value') }}</label>
                                            <input id="min" type="number" class="regTxtBox" name="min"
                                                value="" required autocomplete="min" autofocus
                                                placeholder="Minimum investment value">
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="max" class="">{{ __('Max Investment Value') }}</label>
                                            <input id="max" type="number" class="regTxtBox" name="max"
                                                value="" required autocomplete="max" autofocus
                                                placeholder="Maximum Investment Value">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="daily_interest">{{ __('Package Interest (%)') }}</label>
                                            <input id="daily_interest" step="0.1" type="number" class="regTxtBox"
                                                name="interest" value="" required autocomplete="daily_interest"
                                                autofocus
                                                placeholder="Percentage interest for the whole period of investment">

                                        </div>
                                        <div class="col-sm-6">
                                            <label for="color">{{ __('Icon (NioIcons)') }}</label>
                                            <input id="color" type="text" class="regTxtBox" name="color"
                                                value="" required autocomplete="color" autofocus
                                                placeholder="ni-home-alt">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <label for="period">{{ __('Total Period of Investment(Days)') }}</label>
                                            <input id="period" step="1" type="number" class="regTxtBox"
                                                name="period" value="" required autocomplete="period" autofocus
                                                placeholder="Period of Investment (Days)">
                                        </div>
                                        <div class="col-sm-6">
                                            <label for="interval"
                                                class="">{{ __('Withdrawal Interval (Days)') }}</label>
                                            <input id="interval" type="number" class="regTxtBox" name="interval"
                                                value="" required autocomplete="interval" autofocus
                                                placeholder="Withdrawal interval (Days)">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-12">
                                            <label for="description">{{ __('Description ') }}</label>
                                            <textarea id="description" rows="10" cols="10" class="form-control" name="description" value="" required
                                                autocomplete="desc" autofocus placeholder="Description"></textarea>
                                        </div>
                                    </div>
                                </form>
                                <div class="form-group row">
                                    <div class="col-sm-12 text-center">
                                        <br><br>
                                        <button class="btn btn-warning btn_form"
                                            onclick="load_post_ajax('/admin/create/package', 'add_new_pack', 'add_pack')"><i
                                                class="fa fa-plus"></i> {{ __('Add') }} </button>
                                    </div>
                                </div>

                                <br><br>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    @endSection

resources/views/admin/dashboard.blade.php
@extends('admin.atlantis.layout')
@Section('content')
    <div class="main-panel">
        <div class="content">
            @include('admin.atlantis.main_bar')
            <div class="page-inner mt--5">
                @include('admin.atlantis.overview')
                <div id="prnt"></div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-head-row">
                                    <div class="card-title"> {{ __('Overall Statistics') }} </div>
                                    <div class="card-tools">
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="chart-container @if ($adm->role !== 'admin') {{ $blur_cnt ?? '' }} @endif">
                                    <canvas id="adminStatisticsChart2"></canvas>
                                </div>
                                <div id="adminMyChartLegend2"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-primary @if ($adm->role !== 'admin') {{ $blur_cnt ?? '' }} @endif">
                            <div class="card-header">
                                <div class="card-title"> {{ __('Withdrawal Stats') }} </div>
                            </div>
                            <div class="card-body pb-0">
                                <div class="pull-in">
                                    <canvas id="wd_stats"></canvas>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body pb-0">
                                <div class="px-2 pb-2 pb-md-0 text-center">
                                    <div id="circles-logs"></div>
                                    <h6 class="fw-bold mt-3 mb-0"> {{ __('Activities') }} </h6>
                                    <br>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title"> {{ __('Monthly Breakdown') }} </div>
                            </div>
                            <div class="card-body pb-0">
                                @include('admin.temp.monthly')
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row row-card-no-pd">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-head-row card-tools-still-right">
                                    <h4 class="card-title"> {{ __('User Activities') }} </h4>
                                </div>
                                <p class="card-category">
                                    {{ __('All actions performed users.') }}
                                </p>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="table-responsive">
                                                    <table id="basic-datatables"
                                                        class="display table table-stripped
                                                        table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th> {{ __('Admin') }} </th>
                                                                <th> {{ __('Actions') }} </th>
                                                                <th> {{ __('Date') }} </th>
                                                            </tr>
                                                        </thead>
                                                        <tfoot>
                                                            <tr>
                                                                <th> {{ __('Admin') }} </th>
                                                                <th> {{ __('Actions') }} </th>
                                                                <th> {{ __('Date') }} </th>
                                                            </tr>
                                                        </tfoot>
                                                        <tbody>
                                                            @foreach ($logs as $log)
                                                                <tr>
                                                                    <td>
                                                                        {{ $log->admin }}
                                                                    </td>
                                                                    <td>
                                                                        {{ $log->action }}
                                                                    </td>
                                                                    <td>{{ $log->created_at }}</td>
                                                                </tr>
                                                            @endforeach
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    @endSection

resources/views/admin/inv_packages.blade.php
<?php
    if(Session::has('val'))
    {
        $v = Session::get('val');
        $packs = App\packages::where('user_id', $v)->orwhere('amount', $v)->orwhere('bank', $v)->orwhere('account_no', $v)->orwhere('account_name', $v)->orwhere('status', $v)->orwhere('created_at', 'like', '%'.$v.'%')->orderby('id', 'asc')->paginate(100);
        Session::forget('val');
    }
    else
    {
        $packs = App\packages::orderby('id', 'asc')->paginate(100);
    }
?>
@extends('admin.atlantis.layout')
@Section('content')
        <div class="main-panel">
            <div class="content">
                @include('admin.atlantis.main_bar')
                <div class="page-inner mt--5">
                    @include('admin.atlantis.overview')
                    <div id="prnt"></div>  
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card_header_bg_blue">
                                    <div class="card-head-row card-tools-still-right">
                                        <h4 class="card-title text-white"> <i class="fas fa-briefcase"></i> {{ __('Investment Packages') }} </h4>
                                        <div class="card-tools">
                                            <a href="/admin/create/package" class="btn btn-default"><i class="fa fa-plus"></i> {{ __('Add') }} </a>
                                        </div>                                                                       
                                    </div>
                                </div>
                                <div class="card-body pb-0 table-responsive">
                                   @include('admin.temp.inv_pack') 
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>

            @include('admin.inc.edit_pack')

@endSection

resources/views/admin/user_deposit.blade.php
<?php    
    if(Session::has('val'))
    {
        $v = Session::get('val');
        $deps = App\deposits::where('user_id', 'like', '%'.$v.'%')->orwhere('usn', 'like', '%'.$v.'%')->orwhere('amount', 'like', '%'.$v.'%')->orwhere('bank', 'like', '%'.$v.'%')->orwhere('account_no', 'like', '%'.$v.'%')->orwhere('account_name', 'like', '%'.$v.'%')->orwhere('status', 'like', '%'.$v.'%')->orwhere('created_at', 'like', '%'.$v.'%')->orderby('id', 'desc')->paginate(100);
        Session::forget('val');
    }
    else
    {
        $deps = App\deposits::orderby('id', 'desc')->paginate(50);
    }
    
?>

@extends('admin.atlantis.layout')
@Section('content')
        <div class="main-panel">
            <div class="content">
                @include('admin.atlantis.main_bar')
                <div class="page-inner mt--5">
                    @include('admin.atlantis.overview')
                    <div id="prnt"></div>  
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card_header_bg_blue" >
                                    <div class="card-head-row card-tools-still-right">
                                        <h4 class="card-title text-white" > <i class="fas fa-donate"></i> {{ __('Deposit History') }} </h4>
                                        <div class="card-tools">
                                            <form action="/admin/search/deposit" method="post">
                                                <div class="input-group">
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"> {{ __('Search:') }} </span>
                                                    </div>
                                                    <input type="text" name="search_val" class="form-control" placeholder="Search by Username, Amount, Bank, Date, Capital or Status">
                                                    <div class="input-group-append">
                                                        <button class="btn"><i class="fa fa-search"></i></button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>  
                                        <div class="card-tools">
                                            <a href="{{route('admin.add.deposit')}}" class="btn btn-success" ><i class="fa fa-plus"></i> Add Deposit</a>
                                        </div>                                                                           
                                    </div>
                                </div>
                                <div class="card-body pb-0 table-responsive">
                                    @include('admin.temp.user_deposits')
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
@endSection